---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes
  tags:
    - base_config

- name: enable repos
# Enable the App repo
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644 
  tags:
    - base_config

- name: install base tools and packages
# Install httpie and python-pip packages
  yum:
    name:
      - httpie
      - python-pip
    state: latest
  tags:
    - base_config
